apiVersion: apps/v1
kind: Deployment
metadata:
  name: gravy-traders-products
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gravy-traders-products
  template:
    metadata:
      labels:
        app: gravy-traders-products
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: gravy-traders-products
          #Note: The '{ENVIRONMENT}' token will be substituted with the value of the ENVIRONMENT github secret by github workflow.
          image: gravytradersacr{ENVIRONMENT}.azurecr.io/gravytradersapiproducts:latest
          env:
            - name: KeyVaultEndpoint
              valueFrom:
                secretKeyRef:
                  name: gravy-traders-kv-endpoint
                  key: gravy-traders-kv-endpoint
            - name: ManagedIdentityClientId
              valueFrom:
                secretKeyRef:
                  name: gravy-traders-mi-clientid
                  key: gravy-traders-mi-clientid
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
